spring.application.name=blog-api

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.access-token-ttl=${JWT_ACCESS_TTL}
jwt.refresh-token-ttl=${JWT_REFRESH_TTL}
